# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('genericm2m', '0001_initial'),
        ('base_entity', '0010_auto_20180305_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='WizcardRelatedField',
            fields=[
                ('relatedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='genericm2m.RelatedObject')),
                ('ext_fields', picklefield.fields.PickledObjectField(blank=True, default={}, editable=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('genericm2m.relatedobject', models.Model),
        ),
    ]
