# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_entity', '0011_wizcardrelatedfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wizcardrelatedfield',
            old_name='ext_fields',
            new_name='join_fields',
        ),
    ]
