# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-10 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_entity', '0012_auto_20180323_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseentitycomponentsowner',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
    ]
