# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-31 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('base_entity', '0013_auto_20180510_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseentitycomponentsowner',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_base_entity.baseentitycomponentsowner_set+', to='contenttypes.ContentType'),
        ),
    ]
