# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_entity', '0013_auto_20180104_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentity',
            name='state',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
