# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_entity', '0014_userentity_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseentity',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='baseentity',
            name='is_activated',
        ),
        migrations.AddField(
            model_name='baseentitycomponent',
            name='entity_state',
            field=models.CharField(choices=[(b'CRT', b'Created'), (b'PUB', b'Published'), (b'EXP', b'Expired'), (b'DEL', b'Deleted')], default=b'CRT', max_length=3),
        ),
    ]
