# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_stats_lead_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='entity_pin',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='entity_unpin',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
