# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 03:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_entity', '0010_auto_20180210_0909'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('baseentitycomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_entity.BaseEntityComponent')),
                ('description', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('num_responders', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('base_entity.baseentitycomponent',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[(b'TOF', b'TrueFalse'), (b'SCL', b'ScaleOf1toX'), (b'MCR', b'MultipleChoiceText'), (b'TXT', b'QuestionAnswerText')], default=b'MCR', max_length=3)),
                ('ui_type', models.CharField(choices=[(b'SEL', b'Select'), (b'SLD', b'GradedSlider'), (b'RAD', b'RadioButton'), (b'DRP', b'DropDown'), (b'TEX', b'TextArea'), (b'RTG', b'Rating')], default=b'SEL', max_length=3)),
                ('single_answer', models.BooleanField(default=True)),
                ('question', models.CharField(max_length=250, verbose_name=b'question')),
                ('extra_text', models.BooleanField(default=False)),
                ('num_responders', models.PositiveIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.Poll')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_polls.question_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'poll',
                'verbose_name_plural': 'polls',
            },
        ),
        migrations.CreateModel(
            name='QuestionChoicesBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_text', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('has_user_value', models.BooleanField(default=False)),
                ('user_value', models.IntegerField(blank=True, default=5, null=True)),
                ('has_boolean_value', models.BooleanField(default=False)),
                ('boolean_value', models.BooleanField(default=True)),
                ('response_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoices1ToX',
            fields=[
                ('questionchoicesbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.QuestionChoicesBase')),
                ('low', models.IntegerField(default=0)),
                ('high', models.IntegerField(default=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('polls.questionchoicesbase',),
        ),
        migrations.CreateModel(
            name='QuestionChoicesMultipleChoice',
            fields=[
                ('questionchoicesbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.QuestionChoicesBase')),
                ('question_key', models.CharField(max_length=1)),
                ('question_value', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('polls.questionchoicesbase',),
        ),
        migrations.CreateModel(
            name='QuestionChoicesText',
            fields=[
                ('questionchoicesbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.QuestionChoicesBase')),
            ],
            options={
                'abstract': False,
            },
            bases=('polls.questionchoicesbase',),
        ),
        migrations.CreateModel(
            name='QuestionChoicesTrueFalse',
            fields=[
                ('questionchoicesbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.QuestionChoicesBase')),
                ('true_key', models.CharField(default=b'Yes', max_length=10)),
                ('false_key', models.CharField(default=b'No', max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('polls.questionchoicesbase',),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_userresponse_related', to='polls.QuestionChoicesBase'),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll'),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_userresponse_related', to='polls.Question'),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionchoicesbase',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_polls.questionchoicesbase_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='questionchoicesbase',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.Question'),
        ),
    ]
