# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='state',
        ),
        migrations.AddField(
            model_name='poll',
            name='num_responders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='num_responders',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
