# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['created'], 'verbose_name': 'poll', 'verbose_name_plural': 'polls'},
        ),
        migrations.AddField(
            model_name='question',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
