# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 06:05
from __future__ import unicode_literals

import base.char_trunc
import base.emailField
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_entity', '0010_auto_20180305_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeTemplate',
            fields=[
                ('baseentitycomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_entity.BaseEntityComponent')),
                ('company', base.char_trunc.TruncatingCharField(blank=True, max_length=100)),
                ('title', base.char_trunc.TruncatingCharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', base.char_trunc.TruncatingCharField(default=b'', max_length=50)),
                ('email', base.emailField.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('ext_fields', picklefield.fields.PickledObjectField(blank=True, default={}, editable=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('base_entity.baseentitycomponent', models.Model),
        ),
        migrations.CreateModel(
            name='ScannedEntity',
            fields=[
                ('baseentitycomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_entity.BaseEntityComponent')),
                ('company', base.char_trunc.TruncatingCharField(blank=True, max_length=100)),
                ('title', base.char_trunc.TruncatingCharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', base.char_trunc.TruncatingCharField(default=b'', max_length=50)),
                ('email', base.emailField.EmailField(blank=True, max_length=254)),
                ('event_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('base_entity.baseentitycomponent', models.Model),
        ),
    ]
