# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-24 02:26
from __future__ import unicode_literals

import base.char_trunc
import base.emailField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0002_auto_20180321_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgetemplate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='badgetemplate',
            name='email',
            field=base.emailField.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='badgetemplate',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='badgetemplate',
            name='name',
            field=base.char_trunc.TruncatingCharField(default=b'', max_length=50),
        ),
    ]
