# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 15:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='reco_generated_at',
            field=models.DateTimeField(default=datetime.datetime(2010, 1, 1, 6, 0, tzinfo=utc)),
        ),
    ]
