# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20180307_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='futureuser',
            name='entity_state',
            field=models.CharField(choices=[(b'CRT', b'Created'), (b'PUB', b'Published'), (b'EXP', b'Expired'), (b'DEL', b'Deleted')], default=b'CRT', max_length=3),
        ),
    ]
