# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-31 08:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_futureuser_entity_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='reco_generated_at',
            field=models.DateTimeField(default=datetime.datetime(2009, 12, 31, 18, 30, tzinfo=utc)),
        ),
    ]
