drop table `wizcard`.`wizcardship_wizconnectionrequest`;
drop table `wizcard`.`wizcardship_wizcard_wizconnections`;
drop table `wizcard`.`wizcardship_userblocks_blocks`;
drop table `wizcard`.`wizcardship_userblocks`;
drop table `wizcard`.`wizcardship_contactcontainer`;
drop table `wizcard`.`wizcardship_wizcard`;
drop table `wizcard`.`virtual_table_membership`;
drop table `wizcard`.`virtual_table_virtualtable`;
drop table `wizcard`.`userprofile_userprofile`;
drop table `wizcard`.`notifications_notification`;
drop table `wizcard`.`django_admin_log`;
drop table `wizcard`.`auth_group_permissions`;
drop table `wizcard`.`auth_user_user_permissions`;
drop table `wizcard`.`auth_permission`;
drop table `wizcard`.`auth_user_groups`;
drop table `wizcard`.`auth_group`;
drop table `wizcard`.`auth_user`;
drop table `wizcard`.`location_mgr_locationmgr`;

