# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0007_auto_20180305_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='where',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
