# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 09:19
from __future__ import unicode_literals

import base.char_trunc
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0007_auto_20180210_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeeinvitee',
            name='company',
            field=base.char_trunc.TruncatingCharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attendeeinvitee',
            name='title',
            field=base.char_trunc.TruncatingCharField(blank=True, max_length=200),
        ),
    ]
