# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0008_agendaitem_where'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitorinvitee',
            name='exhibitor',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Campaign'),
        ),
    ]
