# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-09 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0009_exhibitorinvitee_exhibitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitorinvitee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibitor_invitees', to='entity.Event'),
            preserve_default=False,
        ),
    ]
