# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 07:34
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0010_auto_20180116_1220'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='agendaitem',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='agendaitem',
            old_name='agenda',
            new_name='agenda_key',
        ),
    ]
