# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-09 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0010_exhibitorinvitee_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitorinvitee',
            name='exhibitor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exhibitor_invitees', to='entity.Campaign'),
        ),
    ]
