# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-31 08:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0012_auto_20180425_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeeinvitee',
            name='ext_fields',
            field=picklefield.fields.PickledObjectField(blank=True, default={}, editable=False),
        ),
        migrations.AddField(
            model_name='coowners',
            name='permission_bitmap',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='coowners',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coowner_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exhibitorinvitee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibitor_invitees', to='entity.Event'),
        ),
    ]
