# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-01 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0014_auto_20180601_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coowners',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coowner_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
