# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-30 17:26
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0015_auto_20180516_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeeinvitee',
            name='ext_fields',
            field=picklefield.fields.PickledObjectField(blank=True, default={}, editable=False),
        ),
    ]
