# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 07:34
from __future__ import unicode_literals

import base.char_trunc
import base.emailField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taganomy', '0002_auto_20180104_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taganomy',
            name='category',
        ),
        migrations.AddField(
            model_name='taganomy',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='taganomy',
            name='email',
            field=base.emailField.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='taganomy',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='taganomy',
            name='name',
            field=base.char_trunc.TruncatingCharField(default=b'', max_length=50),
        ),
    ]
