# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20171128_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncNotification',
            fields=[
                ('basenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.BaseNotification')),
                ('delivery_period', models.PositiveSmallIntegerField(choices=[(1, b'RECUR'), (2, b'INSTANT'), (3, b'SCHEDULED')], default=2)),
                ('last_tried', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, b'success'), (-1, b'failed'), (1, b'new')], default=1)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            bases=('notifications.basenotification',),
        ),
        migrations.CreateModel(
            name='SyncNotification',
            fields=[
                ('basenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.BaseNotification')),
                ('acted_upon', models.BooleanField(default=True)),
            ],
            bases=('notifications.basenotification',),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='basenotification_ptr',
        ),
        migrations.AddField(
            model_name='basenotification',
            name='do_push',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basenotification',
            name='notification_text',
            field=models.CharField(default=b'', max_length=254),
        ),
        migrations.AddField(
            model_name='basenotification',
            name='readed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
