# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20180201_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asyncnotification',
            name='notifcation_text',
        ),
        migrations.RemoveField(
            model_name='basenotification',
            name='delivery_mode',
        ),
        migrations.AddField(
            model_name='basenotification',
            name='do_push',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basenotification',
            name='notification_text',
            field=models.CharField(default=b'', max_length=254),
        ),
    ]
