# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20180210_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='basenotification',
            name='notif_operation',
            field=models.CharField(default=b'', max_length=1),
        ),
    ]
