# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-31 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20180501_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='basenotification',
            name='exception_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
